### ISSUE TITLE
Question on Scope and Usage for Very Short Text

### ISSUE THREAD

**Issue by Mrs-Hudson** [halolimat/LNEx#19]
Hi, will LNEx work on very short text having just the entity name and possibly a location? For example: '
Parliament House, New Delhi',  => 'New Delhi'
'IBM, Israel',  => 'Israel'
'Carnegie Mellon University Silicon Valley' => 'Silicon Valley'
'Micorsoft' => null

My use case does not have much context , can I still try LNEx?
Thanks

**Comment by halolimat** [comment]
Hi. Yes, LNEx should be able to extract the location names from any text regardless of the length. However, the dictionary/gazetteer should be created for a specific region. The reason why that is important is because we are motivated by the geocoding step so we would like to minimize ambigioutities as much as possible. In other words, don't expect LNEx to be a general purpose location Name extractor as Yahoo Place Finder.

Cheers, 
Hussein
